all:
	cd .. && vim manifest.json +"normal gg12jLhh" && zip -r ./UPLOAD/DFG_Live_Extension.zip app.js  background.js  calendar.png  dialog.html  fonts  icon_OFFLINE.png  icon_ONLINE.png  icons   manifest.json  popup.html  style.css
